name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.0
        cache: 'npm'

    - run: npm ci
    - run: npm run build
    
